### ISSUE TITLE
Uninitialized helper variable leads to very long sleep

### ISSUE THREAD

**Issue by Olstyle** [jefftenney/LPTIM-Tick#15]
Playing around with unitialized bss (helps the startup time from Standby, yes I informed the compiler about that configuration) I noticed that `isTickNowSuppressed` https://github.com/jefftenney/LPTIM-Tick/blob/b9ff0b7111ef486ecfa41afb0afc56fdb00685e1/Core/Src/lptimTick.c#L238 starting up with a non zero value leads to a very long sleep when the ISR is first reached and `vPortSuppressTicksAndSleep `has not happend before.
I have not reviewed the other helpers to be honest, but I can clearly see on a target that initializing that specific variable to zero fixes my project. E.g. `isCmpWriteInProgress` might be problematic as well.

**Comment by jefftenney** [comment]
Hi Oliver -- I have never used standby or shutdown myself, so I missed this issue completely.  I had never considered bss not being reset.

What is the condition of LPTIM after standby?  The reference manual implies it is reset.  In that case, the code in `vPortSetupTimerInterrupt()` would need to run, and that would be a good place to reset both `isTickNowSuppressed` and `isCmpWriteInProgress`.  Are you calling `vTaskStartScheduler()` after standby?  It's not clear to me how much application state you are preserving through standby.

Thanks for identifying this issue.

**Comment by Olstyle** [comment]
Basically you start again from the interrupt vector and run the startup code again (and also initialize the scheduler again etc.). So static initializers will be reset by the startup loading of .text. . It _could_ also reset the whole .bss to zero, but on devices with a lot of RAM this takes an unreasonable time to do, so I removed that from my project setup.

**Comment by jefftenney** [comment]
I will add code soon to reset those two variables in 'vPortSetupTimerInterrupt()' soon.

On a related note, you can drastically speed up clearing of bss in 2 ways.

1. Use __no_init or equivalent when declaring large buffers.

2. Improve C startup code provided by ST.

'''
/* Zero fill the bss segment. */ 
  
     movs R0, #0 
     ldr  R1, =_sbss         /* Write 0 to @R1 */ 
     ldr  R2, =_ebss         /* Until R1 == R2 */ 
     b    ZeroBssTermCheck 
  
 ZeroBss: 
     str  R0, [R1], #4 
 ZeroBssTermCheck: 
     cmp  R1, R2 
     bne  ZeroBss
'''

The code above gives a 40% reduction in execution time compared to ST code.

**Comment by Olstyle** [comment]
Thank you for both the fast reaction and the suggestions. I might try a no_init `configAPPLICATION_ALLOCATED_HEAP`, this should be the biggest thing in bss.
